<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(apply_filters('cardealer_acf_make_an_offer', array (
	'key' => 'group_58da3afeae750',
	'title' => esc_html__('Make an Offer', 'cardealer-header'),
	'fields' => array (
		array (
			'key' => 'field_591ed0c6c228a',
			'label' => esc_html__('User Information', 'cardealer-header'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name- acf_field_name- acf_field_name-',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_58da3b08c61cc',
			'label' => esc_html__('First Name', 'cardealer-header'),
			'name' => 'first_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-first_name acf_field_name-first_name acf_field_name-first_name acf_field_name-first_name acf_field_name-first_name',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_58da3b22c61cd',
			'label' => esc_html__('Last Name', 'cardealer-header'),
			'name' => 'last_name',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-last_name acf_field_name-last_name acf_field_name-last_name acf_field_name-last_name acf_field_name-last_name',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_58da3b2cc61ce',
			'label' => esc_html__('Email Id', 'cardealer-header'),
			'name' => 'email_id',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-email_id acf_field_name-email_id acf_field_name-email_id acf_field_name-email_id acf_field_name-email_id',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_58da3b46c61cf',
			'label' => esc_html__('Home Phone', 'cardealer-header'),
			'name' => 'home_phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-home_phone acf_field_name-home_phone acf_field_name-home_phone acf_field_name-home_phone acf_field_name-home_phone',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_58da3b57c61d0',
			'label' => esc_html__('Comment', 'cardealer-header'),
			'name' => 'comment',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-comment acf_field_name-comment acf_field_name-comment acf_field_name-comment acf_field_name-comment',
				'id' => '',
			),
			'default_value' => '',
			'new_lines' => 'wpautop',
			'maxlength' => '',
			'placeholder' => '',
			'rows' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_58da3b64c61d1',
			'label' => esc_html__('Request Price', 'cardealer-header'),
			'name' => 'request_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-request_price acf_field_name-request_price acf_field_name-request_price acf_field_name-request_price acf_field_name-request_price',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ecde3cdabe',
			'label' => esc_html__('Car Information', 'cardealer-header'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name- acf_field_name- acf_field_name-',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_591ecdf5cdabf',
			'label' => esc_html__('Car Year', 'cardealer-header'),
			'name' => 'car_year_inq',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-car_year_inq acf_field_name-car_year_inq acf_field_name-car_year_inq',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece00cdac0',
			'label' => esc_html__('Car Make', 'cardealer-header'),
			'name' => 'car_make_inq',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-car_make_inq acf_field_name-car_make_inq acf_field_name-car_make_inq',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece0acdac1',
			'label' => esc_html__('Car Model', 'cardealer-header'),
			'name' => 'car_model_inq',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-car_model_inq acf_field_name-car_model_inq acf_field_name-car_model_inq',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece0fcdac2',
			'label' => esc_html__('Car Trim', 'cardealer-header'),
			'name' => 'car_trim_inq',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-car_trim_inq acf_field_name-car_trim_inq acf_field_name-car_trim_inq',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece16cdac3',
			'label' => esc_html__('VIN Number', 'cardealer-header'),
			'name' => 'vin_number',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-vin_number acf_field_name-vin_number acf_field_name-vin_number',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece1ccdac4',
			'label' => esc_html__('Stock number', 'cardealer-header'),
			'name' => 'stock_number',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-stock_number acf_field_name-stock_number acf_field_name-stock_number',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece22cdac5',
			'label' => esc_html__('Regular Price', 'cardealer-header'),
			'name' => 'regular_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-regular_price acf_field_name-regular_price acf_field_name-regular_price',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
		array (
			'key' => 'field_591ece28cdac6',
			'label' => esc_html__('Sale Price', 'cardealer-header'),
			'name' => 'sale_price',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => 'acf_field_name-sale_price acf_field_name-sale_price acf_field_name-sale_price',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 1,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'make_offer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
	'menu_item_level' => 'all',
)));

endif;
?>